//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Foolproof;

namespace PhoneCardsMVC.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Contact
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Bu Alan Zorunludur")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Bu Alan Zorunludur")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Bu Alan Zorunludur")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Bu Alan Zorunludur")]
        public int GroupId { get; set; }
        public string GroupName { get; set; }




        [RequiredIf("GroupId", 1, ErrorMessage = "Bu Alan Zorunludur")]
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }

        public Nullable<int> DepartmentId { get; set; }
        public string DepartmentName { get; set; }


        [RequiredIf("GroupId", 2,ErrorMessage = "Bu Alan Zorunludur")]
        public Nullable<int> ConsultantTypeId { get; set; }
        public string ConsultantTypeName { get; set; }

        public Nullable<int> TitleId { get; set; }
        public string TitleName { get; set; }

        public bool IsActive { get; set; }

        public virtual Title Title { get; set; }
        public virtual Company Company { get; set; }
        public virtual ConsultantType ConsultantType { get; set; }
        public virtual Department Department { get; set; }
        public virtual Group Group { get; set; }
    }
}
